### ISSUE TITLE
NullReferenceException for route tests since upgrading to 1.2.3

### ISSUE THREAD

**Issue by paulduran** [ivaylokenov/MyTested.WebApi#261]
I updated to 1.2.3 and several unit tests that worked fine in 1.2.2 have now stopped working. 

The failing tests have two things in common:

* all specifying .WithHttpMethod() of PUT or POST
* all passing null as the expected parameter value

For example

```
        [Fact]
        public void VerifySingleSignOnAsBusiness()
        {
            MyWebApi.Routes().ShouldMap("http://dummyhost.com/api/v2/business/39/singlesignon").WithHttpMethod(HttpMethod.Post).To<SingleSignOnController>(c=>c.Post(null));
        }
```

Here is the stack trace:

```
Object reference not set to an instance of an object.

   at MyTested.WebApi.Builders.Routes.ShouldMapTestBuilder.<>c__DisplayClass5`1.<ValidateRouteInformation>b__4(KeyValuePair`2 arg)
   at MyTested.WebApi.Common.Extensions.EnumerableExtensions.ForEach[T](IEnumerable`1 collection, Action`1 action)
   at MyTested.WebApi.Builders.Routes.ShouldMapTestBuilder.ResolveTo[TController](LambdaExpression actionCall)
   at MyApp.Tests.WebApiRouteTests.VerifyTerminateEmployeeInPayRun() in C:\projects\Basics\MyApp\MyApp.Tests\WebApiRouteTests.cs:line 111
```

Let me know if there's any other information I can give you.

**Comment by ivaylokenov** [comment]
@paulduran Got it. It is a quick fix, will update the package in the next couple of hours. Sorry for the inconvinience caused.

**Comment by ivaylokenov** [comment]
@paulduran Fixed in version 1.2.4. It is available on NuGet.

**Comment by paulduran** [comment]
@ivaylokenov works a treat now, thanks heaps for being so responsive in making those changes!

**Comment by ivaylokenov** [comment]
@paulduran You are welcome. :+1:
